// Single source of truth for the in-page nav and each page's <head>
// metadata. Edit this file (and src/pages/*.html for content) —
// public/*.html is generated by scripts/build.mjs and should not be
// hand-edited.

// This is a one-page site (index.html) with the main nav linking to
// sections on that same page, plus a 404 page that intentionally has no
// header/nav of its own.
export const NAV = [
  { href: '#help', label: 'Get help' },
  { href: '#donate', label: 'Donate' },
  { href: '#volunteer', label: 'Volunteer' },
  { href: '#contact', label: 'Contact' },
];

export const PAGES = [
  {
    slug: 'index',
    title: 'Kington Foodbank',
    description: 'Kington Foodbank offers a friendly welcome and a bag of essentials to anyone in Kington and the surrounding villages who needs a hand. Open every Friday at the Parish Hall.',
    header: true,
  },
  {
    slug: '404',
    title: "Page not found — Kington Foodbank",
    description: "This page couldn't be found. Find your way back to Kington Foodbank's home page.",
    header: false,
    canonical: false,
    robots: 'noindex',
  },
];
